// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/foundation.dart';
import 'firebase_options.dart';
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs4u3zi9n5Lm94BbteeUjK-OMLfsbTUAE',
    appId: '1:988887443301:web:08630d4c231454e392a38c',
    messagingSenderId: '988887443301',
    projectId: 'car-rental-5ea33',
    authDomain: 'car-rental-5ea33.firebaseapp.com',
    storageBucket: 'car-rental-5ea33.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWwOhhlkeDX9d_idfe1pEZojbZ6KHxwaw',
    appId: '1:988887443301:android:7e0baf63f6d917bc92a38c',
    messagingSenderId: '988887443301',
    projectId: 'car-rental-5ea33',
    storageBucket: 'car-rental-5ea33.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuhesIf1DzbctR3pdYrbhKqtQnUfTDflI',
    appId: '1:988887443301:ios:d4729cf0c7101c7692a38c',
    messagingSenderId: '988887443301',
    projectId: 'car-rental-5ea33',
    storageBucket: 'car-rental-5ea33.firebasestorage.app',
    iosBundleId: 'com.example.untitled2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBs4u3zi9n5Lm94BbteeUjK-OMLfsbTUAE',
    appId: '1:988887443301:web:935547fd080104df92a38c',
    messagingSenderId: '988887443301',
    projectId: 'car-rental-5ea33',
    authDomain: 'car-rental-5ea33.firebaseapp.com',
    storageBucket: 'car-rental-5ea33.firebasestorage.app',
  );
}
